### DISCUSSION TITLE
How to access container inside docker network?

### DISCUSSION THREAD

**Discussion by cavoq** [kartoza/docker-geoserver#644] [Q&A]
Basically what i have is a docker-compose.yml file where i spin up a custom postgres container and some other services. I have a custom network for this, since i don't want to run on the host network within my Pipeline. When i run my my server using this definition:

```
  geoserver:
    networks:
      - geoserver-net
    image: 'kartoza/geoserver:2.25.0'
    restart: 'unless-stopped'
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - ./settings:/settings
    environment:
      GEOSERVER_CONTEXT_ROOT: geoserver
      GEOSERVER_ADMIN_PASSWORD: myawesomegeoserver
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
      GEOWEBCACHE_CACHE_DIR: /opt/geoserver/data_dir/gwc
      INITIAL_MEMORY: 2G
      MAXIMUM_MEMORY: 4G
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_PORT: 5432
      RECREATE_DATADIR: TRUE
      RUN_AS_ROOT: TRUE # TODO: Use a non-root user
    ports:
      - '8600:8080'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u admin:myawesomegeoserver http://localhost:8080/geoserver/rest/about/version.xml"
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 20s
```

It works fine. But i can't access the geoserver from my other services via the service name "geoserver". I tried mounting a custom ./settings path providing a server.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<Server port="8005" shutdown="SHUTDOWN">
    <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
    <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
    <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
    <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
    <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />

    <Service name="Catalina">
        <Connector port="8080" protocol="HTTP/1.1"
            connectionTimeout="20000"
            address="0.0.0.0"
            redirectPort="8443" />
        <Engine name="Catalina" defaultHost="geoserver">
            <Realm className="org.apache.catalina.realm.LockOutRealm">
                <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
                    resourceName="UserDatabase" />
            </Realm>

            <Host name="geoserver" appBase="webapps"
                unpackWARs="true" autoDeploy="true">

                <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
                    prefix="localhost_access_log" suffix=".txt"
                    pattern="%h %l %u %t &quot;%r&quot; %s %b" />

            </Host>
        </Engine>
    </Service>
</Server>
```

Do i need to change or add something in my server.xml? Is there an easy way to make geoserver accessible through my docker network?
