### DISCUSSION TITLE
GEOSERVER WFS LAYER DOESN'T RENDER PROPERLY ON QGIS AND REACT-LEAFLET

### DISCUSSION THREAD

**Discussion by RafaelZamberlan** [kartoza/docker-geoserver#656] [Q&A]
I think the problem must be a configuration on geoserver, i did the "default" way to upload layer, created workspace, store, layer, etc etc... 
Seen some leaflet-geoserver-request but i couldnt implement in my react-leaflet 
This is how i implement the layer inside MapComponent:

```
  //Linhas de plantio
    fetch('http://localhost:83/geoserver/SAIVIEW/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=SAIVIEW:analise_plantio&outputFormat=application%2Fjson&srsName=EPSG:4326')
    .then(response => response.json())
    .then(data => setlinhaplantioData(data));



        {/*Linha_plantio*/}
        {linhaplantio && linhaplantioData && <GeoJSON data={linhaplantioData}
        style={(feature) => ({
          color: feature.properties.PLANTIO2 === "Sem Falha" ? 'green' : 'red', // a cor da linha
          fillColor: feature.properties.PLANTIO2 === "Sem Falha" ? 'green' : 'red', // cor do preenchimento
          fillOpacity: 0.1, // opacidade do preenchimento
          weight: 2
        })}
        
        
```
My docker-compose:
```
version: "3.8"
services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.23.0
    restart: always
    environment:
      - SKIP_DEMO_DATA=true
      - CORS_ENABLED=true
    volumes:
      - ./docker/geoserver/dados:/opt/dado
      - ./docker/geoserver/geoserver_data:/opt/geoserver_data:rw
      - ./web.xml:/opt/apache-tomcat-9.0.68/webapps/geoserver/WEB-INF/web.xml
    ports:
      - 83:8080
      
```
      
QGIS (should be getting the red layer, not the green one, they are both the same, the green one its being provided by geoserver (docker) 
![Captura de tela 2024-05-24 162800](https://github.com/tomickigrzegorz/react-leaflet-examples/assets/105324487/86f5c126-6a52-4acf-8d01-6a70af45acaa)
webgis react-leaflet:
![Captura de tela 2024-05-24 162715](https://github.com/tomickigrzegorz/react-leaflet-examples/assets/105324487/126fc8a4-398b-4cdc-a063-5081e9866e6b)
openlayers, 100% right as should be 
![Captura de tela 2024-05-24 163014](https://github.com/tomickigrzegorz/react-leaflet-examples/assets/105324487/d801ec6a-2511-4eae-8a4a-fe0138c4077b)
