### ISSUE TITLE
Release 2.16 on docker hub

### ISSUE THREAD

**Issue by vjanssens** [kartoza/docker-geoserver#118]
Geoserver 2.16 has been committed in ([afb2b8d](https://github.com/kartoza/docker-geoserver/commit/afb2b8db78b1717e05ff0d9ef19688a15f5101d9)), but is not yet available on docker hub. Can you make a release so we can download the latest version from docker hub?
I see `latest` points to 2.16, but I'd like to stick to a specific version.

**Comment by Nkmol** [comment]
Note that you can use [build args](https://docs.docker.com/compose/compose-file/#build) to install your own GeoServer version and overwrite the [`ARGS GS_VERSION`](https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile#L10) with your own value.

A _docker-compose.yml_ example that worked for me:


```
  geoserver:
    build:
      context: 'https://github.com/kartoza/docker-geoserver.git'
      args: 
        GS_VERSION: 2.16.1
    image: 'kartoza/geoserver:2.15.2'
```
