### ISSUE TITLE
Increasing java memory

### ISSUE THREAD

**Issue by SamyOteroGlez** [kartoza/docker-geoserver#196]
Hi all,

I am having problems defining/working with the memory java is able to allocate by default.

According to the documentation if I define the values for:
```
INITIAL_MEMORY=<size> : Initial Memory that Java can allocate, default 2G
MAXIMUM_MEMORY=<size> : Maximum Memory that Java can allocate, default 4G
```
I can increase java memory usage (Xms and Xmx).

Unless I am looking in the wrong place, it is not affecting those values inside the container.

Here is part of my docker-compose file where I define the min and max to be 4G and 8G respectively.
```
version: '3.3'
services:
  geo_test_ram:
    image: kartoza/geoserver:2.16.1
    environment:
      GEOSERVER_ADMIN_PASSWORD: my-pass
      INITIAL_MEMORY: 4G
      MAXIMUM_MEMORY: 8G
.
.
.
```

Once the container is up and running, I ssh into it and run the following command `java -XX:+PrintFlagsFinal -version | grep HeapSize` to verify the values (values are in bytes). 
Here is the output:
```
    uintx ErgoHeapSizeLimit                         = 0                                         {product}
    uintx HeapSizePerGCThread                   = 87241520                            {product}
    uintx InitialHeapSize                               := 264241152                           {product}
    uintx LargePageHeapSizeThreshold       = 134217728                           {product}
    uintx MaxHeapSize                                 := 4206886912                          {product}
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
I am expecting the `MaxHeapSize` and `InitialHeapSize` to be closer to 8G and 4G. 

Any help will be appreciated.

Thanks
