### ISSUE TITLE
Cannot route to geoserver container when app is deployed online.

### ISSUE THREAD

**Issue by mcfwesh** [kartoza/docker-geoserver#204]
For some days, I have been trying to route to my geoserver container and get map tiles in my application after deploying it online. The name of my container is `geoserver`, and the ports are `8443:8443`. I make a request from my frontend like so: `http://geoserver:8443/.....` to get the tiles, but I get no response. Bear in mind, that in development, this totally works with `localhost`. I really need help because I have been struggling with it for more than a week now. 

docker-compose-prod file:
```
version: "3"

services:
  traefik:
    hostname: traefik
    image: traefik:v1.7
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:domain"
      - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./shared:/shared:ro
    networks:
      - proxy

  geoserver:
    container_name: "geoserver"
    build:
      context: ./docker-geoserver
      dockerfile: Dockerfile
    volumes:
      - ./data:/opt/geoserver/data_dir
    networks:
      - proxy
    restart: "always"
    ports:
      - "8443:8443"
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
      - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}

  h2-atlas:
    container_name: "h2-atlas"
    build:
      context: ./client
      dockerfile: Dockerfile.production
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=example_backend"
      - "traefik.frontend.rule=Host:domain"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    restart: "always"
    external_links:
      - geoserver

networks:
  proxy:
    external: true

```
Am I missing anything?
Thanks for your anticipated response
