### ISSUE TITLE
cannot load custom fonts

### ISSUE THREAD

**Issue by iosefa** [kartoza/docker-geoserver#237]
I am trying to load custom fonts to use in my sld labels but it seems that none of my loaded fonts are being installed.

I am using the ` kartoza/geoserver:2.18.0` image. And here is how I am trying to add the fonts:

I copied the `.ttf` files into a `fonts` directory and I mount this volume in docker-compose. Here is the geoserver service as defined in my docker-compose file:

```yml
  geoserver:
    image: kartoza/geoserver:2.18.0
    ports:
      - 8600:8080
    env_file: .env
    volumes:
      - ./fonts:/opt/fonts
      - geoserver:/opt/geoserver/data_dir
    restart: always
    depends_on:
      - postgres
```

The contents of my `fonts` directory are:

```bash
ls fonts
NotoSans-Bold.ttf       NotoSans-BoldItalic.ttf NotoSans-Italic.ttf     NotoSans-Regular.ttf
```

And in the docker container (after connecting via `docker-compose exec geoserver bash`) the fonts are copied to the `$FONTS_DIR`:

```bash
geoserveruser@e052ba9c7749:/usr/local/tomcat$ ls ${FONTS_DIR}/*.ttf
/opt/fonts/NotoSans-Bold.ttf  /opt/fonts/NotoSans-BoldItalic.ttf  /opt/fonts/NotoSans-Italic.ttf  /opt/fonts/NotoSans-Regular.ttf
```

However, dont see these in the `truetype` directory:

```bash
geoserveruser@e052ba9c7749:/usr/local/tomcat$ ls /usr/share/fonts/truetype/
aenigma  dejavu  fonts-georgewilliams  msttcorefonts  sjfonts  ttf-bitstream-vera
```

When I observe the docker-compose logs, I notice that there are permissions issues:

```bash
 docker-compose logs geoserver     
Attaching to internal_geoserver_1
geoserver_1     | cp: cannot create regular file '/usr/share/fonts/truetype/NotoSans-Bold.ttf': Permission denied
geoserver_1     | cp: cannot create regular file '/usr/share/fonts/truetype/NotoSans-BoldItalic.ttf': Permission denied
geoserver_1     | cp: cannot create regular file '/usr/share/fonts/truetype/NotoSans-Italic.ttf': Permission denied
geoserver_1     | cp: cannot create regular file '/usr/share/fonts/truetype/NotoSans-Regular.ttf': Permission denied
geoserver_1     | Adding custom projection directory
geoserver_1     | Installing default data directory
...
```

Is this somehow related to Perhaps this is related to https://github.com/kartoza/docker-geoserver/issues/198 ? The files are not owned by root.

Am I missing a crucial step to use custom fonts? 

Thank you!
