### ISSUE TITLE
Password changes not working with docker-compose-build.yml

### ISSUE THREAD

**Issue by mikepianka** [kartoza/docker-geoserver#245]
First off, just want to say thanks for this great image. I'm having an issue changing the admin password when building with `docker-compose-build.yml`. I change the password in the `.env` and then run a build. When inspecting in Docker desktop, I see that `GEOSERVER_ADMIN_PASSWORD` has been changed, but if I try to login to Geoserver only the default `myawesomegeoserver` password works. I also tried making a separate `.env.prod` file and passing it in like `docker-compose --env-file .env.prod ...` but that didn't change the result. Any ideas? Thanks!

**Comment by NyakudyaA** [comment]
@mikepianka what branch are you using. Can you try the develop branch.

**Comment by mikepianka** [comment]
I was using master. I can give develop a try.

**Comment by mikepianka** [comment]
On develop, it seems like it registers the password change because I can no longer login with the default `myawesomegeoserver`, but unfortunately the new password does not work either for login so you are just locked out of Geoserver.

**Comment by mikepianka** [comment]
I tried using an older version, 2.18.2, but it seems to have the same issue.

**Comment by anderson-lactec** [comment]
Same problem here, I changed the password and replace data_dir folder. After this, the password not working anymore.
So, I removed the image and build again, and the default password not worked more.

**Comment by NyakudyaA** [comment]
@anderson-lactec Does it only happen when you use docker compose ?

**Comment by anderson-lactec** [comment]
@NyakudyaA , I don't know, but I think yes. The password 'geoserver' worked. I my case, now I changed to get data_dir in my host and not the volume.

**Comment by anilnatha** [comment]
I'm experiencing this issue but with a normal `docker-compose.yml` file that pulls the image from Docker hub. I tried loading the password through the `.env` file and by using secrets, neither worked for me.  The password for geoserver never updated and the only way I could access the admin interfaces was by using the default geoserver password.

Here is my `docker-compose.yml` that makes use of secrets.

```
version: "3.9"

services:
  db:
    container_name: 'db'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB_PASSWORD_FILE=/run/secrets/POSTGRES_PASS
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
    healthcheck:
        test: "exit 0"
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    ports:
      - "25434:5432"
    secrets:
      - POSTGRES_PASS
    restart: on-failure
    volumes:
      - "./db/data:/var/lib/postgresql"

  geoserver:
    container_name: 'geoserver'
    depends_on:
        db:
          condition: service_healthy
    environment:
        - GEOSERVER_ADMIN_PASSWORD_FILE=/run/secrets/GEOSERVER_ADMIN_PASSWORD
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    image: kartoza/geoserver:${GS_VERSION}
    ports:
      - "8600:8080"
    restart: on-failure
    secrets:
      - GEOSERVER_ADMIN_PASSWORD
    volumes:
      - "./geoserver/data:/opt/geoserver/data_dir"
      - "./geoserver/app-data:/home/geoserveruser/app-data"
      - "./geoserver/logs:/logs"

secrets:
  GEOSERVER_ADMIN_PASSWORD:
    file: ./geoserver/secrets/GEOSERVER_ADMIN_PASSWORD.txt
  POSTGRES_PASS:
    file: ./db/secrets/POSTGRES_PASSWORD.txt
```
