### ISSUE TITLE
Layer Groups disappear after restart 

### ISSUE THREAD

**Issue by alxcost** [kartoza/docker-geoserver#274]
Hi,

I'm launching GeoServer using the following docker-compose script:

```
version: '3'

services:
  geoserver:
    image: kartoza/geoserver:latest # DockerHub Digest: 9e8df3262b02
    restart: always
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./datasets:/opt/datasets
    environment:
      - STABLE_EXTENSIONS=importer-plugin
      - MAXIMUM_MEMORY=3G

volumes:
  geoserver_data:
```

After launching I create a layer group called `Test/Digital Elevation Models (Difference)`
But whenever I restart the container, any Layer Group that I've created seems to just disappear and becomes inaccessible through any protocol (WMS, WFS, etc...).

If I try to create it again, it gives me an error `No GeoServerTileLayer named 'Test/Digital Elevation Models (Difference)' exists`.

All other data seems to be ok, including actual Layers, workspaces, etc...

Any idea what could be causing this?
