### ISSUE TITLE
Unable to set the username and the password of the Geoserver's admin user using env variables

### ISSUE THREAD

**Issue by athanasp** [kartoza/docker-geoserver#326]
I am trying to set the username and the password of the Geoserver's admin user in  docker image by setting the enviroment variables:
- *GEOSERVER_ADMIN_USER*,  
- *GEOSERVER_ADMIN_PASSWORD* (or *GEOSERVER_ADMIN_PASSWORD_FILE*). 

Although the values of the aforementioned enviroment variables are passed in the kubernetes pod (verify it via `env`), the geoserver instance uses always the default username and the password of the Geoserver's admin user (`admin` and `geoserver` respectively).

You can reproduce it using the docker image tag: `kartoza/geoserver:2.20.0`.

Deployment environment: `kubernetes`

**Comment by aulemahal** [comment]
I confirm having the same issue. I simply followed the instructions in the readme (https://github.com/kartoza/docker-geoserver#local-build-using-repository-checkout), didn't change anything anywhere. Also tried changing the password in the `.env` file, same thing : the only login that works is admin/geoserver.

**Comment by NyakudyaA** [comment]
> I confirm having the same issue. I simply followed the instructions in the readme (https://github.com/kartoza/docker-geoserver#local-build-using-repository-checkout), didn't change anything anywhere. Also tried changing the password in the `.env` file, same thing : the only login that works is admin/geoserver.

I have tested this on a brand new machine and it's all working
![pull-img](https://user-images.githubusercontent.com/2510900/142976205-842f255e-8148-42c8-9e1a-cf9058b88816.png)

Logging into GeoServer also works
![user-cred](https://user-images.githubusercontent.com/2510900/142976226-daf0facf-3df5-4577-b8e6-3017855d76f7.gif)

Can you please describe your setup. Are you using docker-volumes or a host mounted volume

**Comment by jt-helsinki** [comment]
Same issues using `docker-compose`. 

This is my Geoserver entry:

```
  geoserver:
    image: kartoza/geoserver:2.20.0
    volumes:
      - ./data/geoserver:/opt/geoserver/data_dir
    ports:
      - 8084:8080
    restart: on-failure
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - FOOTPRINTS_DATA_DIR=/opt/geoserver/data_dir/footprints
      - TOMCAT_USER=admin
      - TOMCAT_PASSWORD=password
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_PASSWORD=password
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_FILEBROWSER_HIDEFS=false
      - ENABLE_JSONP=true
      - STABLE_EXTENSIONS=mbstyle-plugin,vectortiles-plugin
      - COMMUNITY_EXTENSIONS=mbtiles-store-plugin,mbtiles-plugin
    healthcheck:
      test: curl --fail -s http://localhost:8084/ || exit 1
```

Both admin/password and admin/geoserver UN/PW combos don't work.
