### ISSUE TITLE
How can I set the evn 'CLUSTER_CONFIG_DIR' in the environment of the docker-compose.yml

### ISSUE THREAD

**Issue by PingYufeng** [kartoza/docker-geoserver#330]
I do not  find the  variable 'CLUSTER_CONFIG_DIR' in the file which name is '.env', but I want to set it like setting 'GEOSERVER_DATA_DIR' in the  environment of the docker-compose.yml. How can I do that?

![image](https://user-images.githubusercontent.com/37933036/141668654-40ca3bb3-4ba7-4d20-9e99-6b1f4e7f8e53.png)

```
services:
  master:
    image: kartoza/geoserver:latest
    container_name: master
    privileged: true
    user: root
    volumes:
      - /home/work/cluster/data/GeoserverDataTemp:/opt/geoserver/data_dir1/
    ports:
      - "9091:8080"
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir1/
     # - CLUSTER_CONFIG_DIR=/home/work/cluster/data/GeoserverDataTemp/cluster/master
      - INSTANCE_STRING=master
```

![image](https://user-images.githubusercontent.com/37933036/141668509-a3cfe6cc-5238-4647-b093-ba4e0094fc67.png)

what's more, I try to find the methods of resolution in the dir 'scripts' , I found that it is init some variables , but it don't init the variable  ‘CLUSTER_CONFIG_DIR’. Where are you setting the global variable 'GEOSERVER_DATA_DIR'? I think you set the default values form reading the file '.env', whether I can change the variable  ‘CLUSTER_CONFIG_DIR’ when I change the file 'start.sh or env-data.sh'?

![image](https://user-images.githubusercontent.com/37933036/141668670-f66e5ebe-1d8d-4cd2-9355-50dfb26125e2.png)
![image](https://user-images.githubusercontent.com/37933036/141668680-70597d25-3da7-4a1b-b0da-46fc6b2c25da.png)

![image](https://user-images.githubusercontent.com/37933036/141670025-2fc06af9-06af-473a-b8ae-66ce0a64f8c3.png)

Aother, I see it can set 'RANDOMSTRING' to create a unique CLUSTER_CONFIG_DIR for each instance. 

![image](https://user-images.githubusercontent.com/37933036/141670456-0d7de266-295e-4d2a-a53c-a035dcacaf4c.png)

That is my idea, but I hope you can give some right solutions when I will change the dir  'scripts'  or 'setting', thanks!
