### ISSUE TITLE
version tag is ignored

### ISSUE THREAD

**Issue by rumski20** [kartoza/docker-geoserver#336]
I am attempting to build and run a geoserver container using version `2.19.3`.

I am building it like this in `docker-compose.yml`:
```
  geoserver:
    # build from git repo - allows use of actual software version
    build: https://github.com/kartoza/docker-geoserver.git
    image: kartoza/geoserver:${GS_VERSION}
.......
```
with an environment file that has `GS_VERSION=2.19.3`

I've tried destroying and recreating the image many times and yet this is what I see on the web GUI each time:
![image](https://user-images.githubusercontent.com/6474942/142649855-011a8631-17e4-4fbe-87b6-a90087e4773e.png)

If there is another way to confirm the version of the running container (or image, I suppose), then please let me know and I'll give that a try. Otherwise, all indications are that the version tag I supplied is getting ignored, and it's just using the version specified here:
https://github.com/kartoza/docker-geoserver/blob/849b8679d18645e6b3f7e12ff9d61213133950f1/Dockerfile#L7
