### ISSUE TITLE
RANDOMSTRING and INSTANCE_STRING variables are not considered in the cluster configuration

### ISSUE THREAD

**Issue by francbartoli** [kartoza/docker-geoserver#339]
As per the clustering readme https://github.com/kartoza/docker-geoserver/blob/849b8679d18645e6b3f7e12ff9d61213133950f1/clustering/README.md?plain=1#L13 it is expected to have the possibility to force the name of the cluster config directory for each node and eventually even the instance name.

This is not going to happen as far as I'm experiencing. Evidence with the following docker-compose file:

```yml
version: '3.9'

volumes:
  geoserver-cluster-data:
  geo-db-data:

services:
  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - geo-db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "pg_isready -d gis"
  geobroker:
    image: rmohr/activemq:5.15.9
    restart: on-failure
    healthcheck:
      test: curl --fail -s http://localhost:8161 || exit 1
      interval: 20s
      timeout: 10s
      retries: 10
  gs-node1:
    image: kartoza/geoserver:2.20.0
    volumes:
      - geoserver-cluster-data:/opt/geoserver/data_dir
    ports:
      - "8081:8080"
    environment:
      - BROKER_URL=tcp://geobroker:61616
      - READONLY=disabled
      - CLUSTER_DURABILITY=false
      - CLUSTERING=True
      - TOGGLE_MASTER=true
      - TOGGLE_SLAVE=true
      - EMBEDDED_BROKER=disabled
      - DB_BACKEND=POSTGRES
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - SSL_MODE=allow
      - RANDOMSTRING=23bd87cfa327d47e
      - INSTANCE_STRING=ac3bcba2fa7d989678a01ef4facc4173010cd8b40d2e5f5a8d18d5f863ca976f
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      geobroker:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  gs-node2:
    image: kartoza/geoserver:2.20.0
    volumes:
      - geoserver-cluster-data:/opt/geoserver/data_dir
    ports:
      - "8082:8080"
    environment:
      - BROKER_URL=tcp://geobroker:61616
      - READONLY=disabled
      - CLUSTER_DURABILITY=false
      - CLUSTERING=True
      - TOGGLE_MASTER=true
      - TOGGLE_SLAVE=true
      - EMBEDDED_BROKER=disabled
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - SSL_MODE=allow
    restart: on-failure
    depends_on:
      gs-node1:
        condition: service_healthy
      geobroker:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
```

The stack starts properly with everything healthy but the cluster configuration of the first node doesn't reflect the values from the variables. Screenshots hereafter:

![image](https://user-images.githubusercontent.com/560676/143310724-59a78508-26e0-4b44-a8e7-1a5e740dec6b.png)

![image](https://user-images.githubusercontent.com/560676/143310881-e0042012-14b8-41d2-a4f7-57d66e46f6a2.png)

![image](https://user-images.githubusercontent.com/560676/143311121-e1c95af6-495d-4e81-a476-9b660b6c77df.png)

@NyakudyaA @lucernae do you accept PR eventually? I believe it is pretty useful the possibility to customize them from a user standpoint.

As usual, many thanks for this amazing work!
