### ISSUE TITLE
Can not run in "subfolder" on Proxy

### ISSUE THREAD

**Issue by v1r0x** [kartoza/docker-geoserver#379]
Thank you for your image. It's really easy and straightforward to set up :+1: 
Only thing I don't get to work is to run it with an external reverse proxy.

I want to run my geoserver on `https://PROXY-IP/service/geo`, which works for the start page (should automatically redirect to `/service/geo/geoserver/web`, but doesn't work)
But when I want to login, the `j_spring_security_check` redirects to `https://PROXY-IP/geoserver/web`.
Is there something I am missing? E.g. an env variable to set that subfolder?

Thanks in advance!

My setup is:

Apache Reverse Proxy:
```
ProxyPass "/service/geo/" "http://IP:8080/"
ProxyPassReverse "/service/geo/" "http://IP:8080/"
```

Docker Container on separate Server/VM:
```
version: '3.3'
services:
        geoserver:
                image: kartoza/geoserver
                container_name: geoserver
                restart: always
                ports:
                        - 8080:8080
                volumes:
                        - ./volumes/geoserver:/opt/geoserver/data_dir
                environment:
                        GEOSERVER_PORT: 8080
                        GEOSERVER_ADMIN_USER: admin
                        GEOSERVER_ADMIN_PASSWORD: securepassword
                        RESET_ADMIN_CREDENTIALS: 0
                        GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
                        TOMCAT_EXTRAS: 0
                        ROOT_WEBAPP_REDIRECT: 1
                        EXISTING_DATA_DIR: 1
                        RECREATE_DATADIR: 0
                        HTTP_PROXY_PORT: 443
                        HTTP_PROXY_NAME: PROXY-IP/service/geo/
                        HTTPS_PROXY_NAME: PROXY-IP/service/geo/
                        HTTP_SCHEME: https
                        GEOSERVER_CSRF_DISABLED: 1
```
