### ISSUE TITLE
Geoserver cluster 2.21 not starting

### ISSUE THREAD

**Issue by pixx1** [kartoza/docker-geoserver#422]
Hi! 
I just used your latest cluster image and ran into multiple issues. (docker-compose)
DB, image: kartoza/postgis:14-3.2
master, image: kartoza/geoserver:2.21.0
node,  image: kartoza/geoserver:2.21.0

I get the constant error:
db_1      | 2022-07-06 12:12:35.977 UTC [331] root@gis FATAL:  role "root" does not exist

So this seems to be a postgres problem to me, maybe the wrong user is used internally?

Maybe the second issue is linked to it so i put it here as well.

I can't connect to the geoserver: http://localhost:8081/geoserver/
Tomcat is reachable by http://localhost:8081/
As I saw in the tomcat manager the webapp is not started, and I can't start it either.

When trying it with geoserver version 2.19.0 it works.

Any idea about that problem? I also try to figure out what cause the problem.
If you need more information I'm happy to provide it.

Btw, thanks a lot for your great work!

**Comment by pixx1** [comment]
Okay, for the first problem I found the solution, the health check is maybe obsolete?
in the cluster docker file I found:
PostGIS:
>  healthcheck:
>  test: "pg_isready -d gis"

But in new docker-compose files for PostGIS it is:
> healthcheck:
> test: "exit 0"

**Comment by NyakudyaA** [comment]
pg_is ready should be the proper way to check if the container is healthy. I will update the docker-compose.

On the issue of the cluster. Will need to test and see what is happening as nothing in the cluster logic was changed.

Also as noted by the documentation these community plugins might also not work most in some cases

**Comment by afabiani** [comment]
The docker-compose test could be maybe updated with simething like

```
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSL=FALSE
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"
```
