### ISSUE TITLE
Geoserver 2.21 not starting with extension s3-geotiff-plugin

### ISSUE THREAD

**Issue by arvkonstantin** [kartoza/docker-geoserver#423]
Compose conf:
```
    geoserver:
      image: kartoza/geoserver:2.21.0
      container_name: geoserver
      ports:
        - "8800:8080"
      environment:
        - GEOSERVER_ADMIN_PASSWORD=admin
        - GEOSERVER_ADMIN_USER=admin
        - COMMUNITY_EXTENSIONS=s3-geotiff-plugin
```
logs:
[logs.txt](https://github.com/kartoza/docker-geoserver/files/9069825/logs.txt)
