### ISSUE TITLE
Сhanging GEOSERVER_DATA_DIR breaks the container

### ISSUE THREAD

**Issue by P0linom** [kartoza/docker-geoserver#435]
If `GEOSERVER_DATA_DIR` change to `/opt/geoserver/data` and volume has param `external: true`, then in logs: 

```
Creating /opt/geoserver/data/user_projections directory
mkdir: cannot create directory ‘/opt/geoserver/data/user_projections’: Permission denied
cp: cannot create regular file '/opt/geoserver/data/user_projections/epsg.properties': No such file or directory
```
and many of the same errors, as a result, the geoserver does not start.

docker-compose file:
```
volumes:
   geoserver-data-br:
     external: true

services:
   geoserver-br:
      image: kartoza/geoserver:2.21.0
      volumes:
        - geoserver-data-br:/opt/geoserver/data
      ports:
        - "8600:8080"
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=/opt/geoserver/data
```
