### ISSUE TITLE
Geoserver doesn't run properly on GCP Compute Engine: Wicket is not defined

### ISSUE THREAD

**Issue by Elysium1436** [kartoza/docker-geoserver#448]
I'm trying to run geoserver on gcp with docker and docker-compose, here is the docker-compose file:
```yaml
version: '2.1'

services:
   geoserver:
      image: "kartoza/geoserver:2.21.1"
      volumes:
        - ./geoserver_data:/opt/geoserver/data_dir
      ports:
        - "0.0.0.0:8080:8080"
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
        - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
        - GEOSERVER_ADMIN_PASSWORD=something_other_than_this
        - GEOSERVER_ADMIN_USER=something_other_than_this
      healthcheck:
        test: curl --fail -s http://localhost:8080/geoserver/web || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
```
The website on the route [IP_ADDRESS]:8080/geoserver is this ugly html website
[![ugly html website geoserver][1]][1]

And the console logs are
[![console logs][2]][2]

On my local computer it works just fine. Firewall has every port open. No idea what to do after here. I tried adding an environment variable on the docker-compose file "GEOSERVER_CSRF_DISABLED=true", but no luck.

edit: figured out the problem is only happening on firefox browser, chrome and edge, and mobile chrome works just fine.

  [1]: https://i.stack.imgur.com/AjTRd.png
  [2]: https://i.stack.imgur.com/0JXXq.png
