### ISSUE TITLE
Geoserver webpage not opening on `localhost:8080/geoserver`

### ISSUE THREAD

**Issue by theoway** [kartoza/docker-geoserver#449]
I built the image locally using the dockerfile, and set the ports correctly. When I ran the image with `docker run -p 8080:8080 ...` , localhost:8080 just shows the default tomcat page, like this:
![Screenshot (174)](https://user-images.githubusercontent.com/41969735/193417708-45f66198-98c9-4430-97f6-81b06cc87a9a.png)

When I used the endpoint `localhost:8080/geoserver`, I got this error:
![Screenshot (175)](https://user-images.githubusercontent.com/41969735/193418452-366d9bd1-0a6c-4f24-91cc-e0de438a9406.png)

When I used the **_docker-compose-nginx.yml_**, and opened `http://localhost/geoserver/web/`, I got this:
![Screenshot (176)](https://user-images.githubusercontent.com/41969735/193418488-b264bfbf-b6fb-405f-a080-33bd79fa33d2.png)

**Please let me know how can I view the homepage of geoserver.**

**Comment by NyakudyaA** [comment]
Why not try out the already published images and then revert back

**Comment by theoway** [comment]
@NyakudyaA  Got it working with Nginx using published docker image. I used that image with docker-compose-nginx.yml. It worked!!! 
Here's another thing I need help with.
```
version: '3.9'

volumes:
   geoserver-data:
   geo-db-data:

services:
   geoserver:
      image: kartoza/geoserver
      volumes:
        - ./geoserver-data:/opt/geoserver/data_dir
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
        - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
        - GEOSERVER_ADMIN_PASSWORD=admin
        - GEOSERVER_ADMIN_USER=geoserver
        - INITIAL_MEMORY=4G
        - MAXIMUM_MEMORY=6G
        - COMMUNITY_EXTENSIONS='cog-plugin'
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

   nginx:
     image: nginx
     volumes:
       - ./sites-enabled:/etc/nginx/conf.d:ro
     logging:
       driver: json-file
       options:
         max-size: 200m
         max-file: '10'
     depends_on:
       - geoserver
     ports:
       - "80:80"

```
As you can see, I've added `COMMUNITY_EXTENSIONS='cog-plugin'` yet this plugin didn't get installed.
How can I make sure this plugin gets installed?
