### ISSUE TITLE
kartoza/geoserver can't let me loggin in

### ISSUE THREAD

**Issue by kambei** [kartoza/docker-geoserver#465]
I have [kartoza/geoserver](https://github.com/kartoza/docker-geoserver) that I start with this docker-compose:
```
version: "3.9"
services:

  geoserver:
    image: kartoza/geoserver
    environment:
      - GEOSERVER_ADMIN_USER
      - GEOSERVER_ADMIN_PASSWORD
      - GEOSERVER_CSRF_DISABLED=true
      - JAVA_OPTS
      #- PROXY_BASE_URL
```

running behind Nginx with these configurations:
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
}


server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name geos.mydomain.com;
        ssl_certificate /etc/nginx/ssl/cert/geoserver/geoserver.crt;
        ssl_certificate_key /etc/nginx/ssl/cert/geoserver/geoserver.rsa;

        location /geoserver/ {
                proxy_pass http://geoserver:8080/geoserver/;
                proxy_pass_header Set-Cookie;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

}
```

I can see the geoserver page:
[![enter image description here][1]][1]

But when I try to login it fails:
[![enter image description here][2]][2]
[![enter image description here][3]][3]

Why? How can I solve it?

  [1]: https://i.stack.imgur.com/dV9aK.png
  [2]: https://i.stack.imgur.com/SGaDi.png
  [3]: https://i.stack.imgur.com/rOYzS.png
