### ISSUE TITLE
Geoserver not spinning up in cluster

### ISSUE THREAD

**Issue by krishnaglodha** [kartoza/docker-geoserver#506]
### What is the bug or the crash?

Both Geoserver instances are failing after using default `docker-compose` file in clustering

```
version: '3.9'

volumes:
   geoserver-cluster-data:
   geo-db-data:

services:
   db:
      image: kartoza/postgis:14-3.2
      volumes:
        - geo-db-data:/var/lib/postgresql
      environment:
        - POSTGRES_DB=gis
        - POSTGRES_USER=docker
        - POSTGRES_PASS=docker
        - ALLOW_IP_RANGE=0.0.0.0/0
        - FORCE_SSL=TRUE
      restart: on-failure
      healthcheck:
        test: "pg_isready -d gis"
   master:
      image: kartoza/geoserver:2.21.0
      volumes:
         - geoserver-cluster-data:/opt/geoserver/data_dir
      ports:
        - "8081:8080"
      environment:
        - BROKER_URL=tcp://0.0.0.0:61616
        - READONLY=disabled
        - CLUSTER_DURABILITY=false
        - CLUSTERING=True
        - TOGGLE_MASTER=true
        - TOGGLE_SLAVE=true
        - DB_BACKEND=POSTGRES
        - HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DB=gis
        - POSTGRES_USER=docker
        - POSTGRES_PASS=docker
        - SSL_MODE=allow
        - GEOSERVER_ADMIN_PASSWORD=geoserver
        - GEOSERVER_ADMIN_USER=admin
        #- RANDOMSTRING=23bd87cfa327d47e
        #- INSTANCE_STRING=ac3bcba2fa7d989678a01ef4facc4173010cd8b40d2e5f5a8d18d5f863ca976f
      restart: on-failure
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
   node:
      image: kartoza/geoserver:2.21.0
      volumes:
         - geoserver-cluster-data:/opt/geoserver/data_dir
      ports:
        - "8082:8080"
      environment:
        - BROKER_URL=tcp://master:61616
        - READONLY=disabled
        - CLUSTER_DURABILITY=false
        - CLUSTERING=True
        - TOGGLE_MASTER=true
        - TOGGLE_SLAVE=true
        - EMBEDDED_BROKER=disabled
        - HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DB=gis
        - POSTGRES_USER=docker
        - POSTGRES_PASS=docker
        - SSL_MODE=allow
        - GEOSERVER_ADMIN_PASSWORD=geoserver
        - GEOSERVER_ADMIN_USER=admin
      restart: on-failure
      depends_on:
        master:
          condition: service_healthy
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
```

I also have ActiveMQ running and ports are open 61616 and 8161
<img width="1378" alt="Screenshot 2023-03-10 at 12 08 57 PM" src="https://user-images.githubusercontent.com/47075664/224242161-f9cdff6b-a50d-4013-82c1-e56853814301.png">

### Steps to reproduce the issue

1. Create ActiveMQ Instance `docker run -p 61616:61616 -p 8161:8161 rmohr/activemq` 
2. Run `docker-compose up` for [docker-compose](https://github.com/kartoza/docker-geoserver/blob/develop/clustering/docker-compose.yml) file in clustering folder

### Versions

2.21.0
