### ISSUE TITLE
overlays not working when building dockers based on this docker-image

### ISSUE THREAD

**Issue by stvno** [kartoza/docker-geoserver#54]
We like to enable CORS on geoserver, as per #24, and store this configuration in our own git repo so we can deploy this on various servers. The way we envisioned this, was to create a `docker-compose.yml` with the relevant dockers and have directories per docker image with extra settings:
````yaml
version: '2'
services:
  postgres:
    build: ./docker/postgres/
    container_name: postgres
    ports:
          - 5432:5432
    environment:
          - POSTGRES_DB=db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=pass
          - PG_DATA_DIR=./docker/postgres/data
    volumes:
          - ${PG_DATA_DIR}:${PGDATA}
  geoserver:
      build: ./docker/geoserver/
      container_name: geoserver
      volumes:
          - ${EXT_GEOSERVER_DATA_DIR}:/opt/geoserver/data_dir
      env_file: .env
      ports:
          - 8080:8080
      depends_on:
          - postgres
      expose:
          - 8080
````
in the `docker/geoserver` directory we have a Dockerfile, a data directory and a resources directory

The Dockerfile just states:
```
FROM kartoza/geoserver
```

In the resources directory we've added the web.xml with the CORS headers enabled:
```
14:19 $ tree resources/
resources/
└── overlays
    └── usr
        └── local
            └── tomcat
                └── conf
                    └── web.xml
```
Our believe was that by the geoserver docker would take the content of the resources/overlay directory and overlay this in the docker image when building it. However the resources directory is being ignored. Diving into the `kartoza/docker-geoserver` repo I realized it was never going to work, the resources directory is not mounted but added in the build [step](https://github.com/kartoza/docker-geoserver/blob/master/Dockerfile#L47). Furthermore the contents of the resources directory will be removed in the final step of (setup.sh)[https://github.com/kartoza/docker-geoserver/blob/master/scripts/setup.sh#L227] so even when the mount would work, it will destroy the configuration on disk.

We considered embedding the docker-geoserver repo into our repo and add the necessary configuration files to ./resources but due to the `.gitignore` the settings will not be persistent.

So my question is, how do you envision to add your own resources to a docker image based on the `kartoza/docker-geoserver` image?

And yes I'm aware of #23 but that was the datadirectory which shouldn't be done with `resources` in the first place and also I'm not sure it was really resolved for him/her.
