### ISSUE TITLE
The exposed port modified by nginx cannot be accessed normally

### ISSUE THREAD

**Issue by huifer** [kartoza/docker-geoserver#548]
### What is the bug or the crash?

I modified the nginx port to 8411:80 [doc](https://github.com/kartoza/docker-geoserver/blob/8df28f09c9cac83dda89fb198f4e326c57aadb46/docker-compose-nginx.yml#L57)

The following error occurred
![image](https://github.com/kartoza/docker-geoserver/assets/26766909/84cdde7c-4ba9-48a4-a73d-ab083acbeea0)

I checked http://localhost:8411/geoserver The interface message is shown in the figure
![image](https://github.com/kartoza/docker-geoserver/assets/26766909/58b3a179-4f84-44f4-ae73-80f3b0f471df)

I think the redirect address is incorrect

### Steps to reproduce the issue

![image](https://github.com/kartoza/docker-geoserver/assets/26766909/8ade42f8-c49d-447c-9e83-5f4f472150b2)

### Versions

The version I am using is  https://github.com/kartoza/docker-geoserver/tree/v2.23.0

### Additional context

docker-compose-nginx.yml 
```
version: '3.9'

volumes:
   geoserver-data:
   geo-db-data:

services:
   db:
      image: kartoza/postgis:${POSTGIS_VERSION_TAG}
      volumes:
        - geo-db-data:/var/lib/postgresql
      ports:
        - ${POSTGRES_PORT}:5432
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - FORCE_SSL=TRUE
      restart: on-failure
      healthcheck:
        test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"

   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=geoserver
        - GEOSERVER_ADMIN_USER=admin
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u admin:'geoserver' http://localhost:8080/geoserver/rest/about/version.xml"
        interval: 1m30s
        timeout: 10s
        retries: 3

   nginx:
     image: nginx
     volumes:
       - ./sites-enabled:/etc/nginx/conf.d:ro
     logging:
       driver: json-file
       options:
         max-size: 200m
         max-file: '10'
     depends_on:
       - geoserver
     ports:
       - "8411:80"
```

**Comment by huifer** [comment]
What should I do if I need to modify the ports exposed by nginx.help me . 🙏🏻🙏🏻🙏🏻

**Comment by NyakudyaA** [comment]
Can you please add https://github.com/kartoza/docker-geoserver#proxy-base-url

**Comment by huifer** [comment]
docker-compose.yml 

```
version: '3.9'

volumes:
  geoserver-data:
  geo-db-data:

services:
  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - ./geo-db-data:/opt/geoserver/postgresql
    ports:
      - 32767:5432
    environment:
      - POSTGRES_DB=gis,gwc
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "exit 0"
  geoserver:
    image: kartoza/geoserver:2.21.0
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    restart: on-failure
    environment:
      - STABLE_EXTENSIONS=charts-plugin,db2-plugin,mysql-plugin,authkey-plugin
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_USER=admin
      - INITIAL_MEMORY=1G
      - MAXIMUM_MEMORY=1G
      - HTTP_PROXY_NAME=gis.zen.com
      - HTTP_SCHEME=http
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u admin:'geoserver' http://localhost:8080/geoserver/rest/about/version.xml"
      interval: 1m30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx
    volumes:
      - ./sites-enabled:/etc/nginx/conf.d:ro
    logging:
      driver: json-file
      options:
        max-size: 200m
        max-file: '10'
    depends_on:
      - geoserver
    ports:
      - "8411:80"
 ```

- nginx config 
```
upstream geoserver {
    server geoserver:8080;
}

server {
    listen      80;
    # the domain name it will serve for
    server_name gis.zen.com;
    # max upload size, adjust to taste
    keepalive_timeout  500;
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    send_timeout                600;
    client_max_body_size        5000;
    client_header_timeout       600;
    client_body_timeout         600;
    fastcgi_read_timeout        300;

    location / {
        proxy_pass http://geoserver/;
        proxy_set_header    Host                $host;                      # the host requested by the client
        proxy_set_header    X-Real-IP           $remote_addr;               # the real visitor IP
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for; # the client IP
        proxy_set_header    X-Forwarded-Host    $host:$server_port;         # the host used for the request
        proxy_set_header    X-Forwarded-Proto   $http_x_forwarded_proto;    # the scheme used for the request, http or https
        port_in_redirect off;
        proxy_connect_timeout 600;
    }
    location /geoserver {
        proxy_pass http://geoserver/geoserver;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-for $remote_addr;
        port_in_redirect off;
        proxy_connect_timeout 600;
        proxy_set_header X-Script-Name /geoserver;

    }
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
```

local host file 
```
127.0.0.1 gis.zen.com
```


![image](https://github.com/kartoza/docker-geoserver/assets/26766909/f26bfe2b-6a4b-47c4-9dc2-8ca81469e28a)


@NyakudyaA   What should I do about it, I've tried so many I just can't handle it. Please help me.
