### ISSUE TITLE
 [Fatal Error] :-1:-1: Premature end of file when recreating geoserver container (version 2.23.0)

### ISSUE THREAD

**Issue by Ja-Woj** [kartoza/docker-geoserver#584]
### What is the bug or the crash?

 Geoserver logs : 
[Fatal Error] :-1:-1: Premature end of file 
On re-create attempt of geoserver container
Geoserver has mounted geoserver data dir and geowebcache data dir in form of volumes.
Geoserver has configuration applied via api. During investigation we narrowed down cause of failure to loading user configuration from files (that is located on volumes/ pvc on kubernetes)

### Steps to reproduce the issue

1. run docker compose up using beneath file : 
```
﻿version: '3.9'

volumes:
  geoserver-data:

services:
  geoserver:
    image: kartoza/geoserver:2.23.0
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8600:8080"
    restart: on-failure
    environment:
        - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
        - GEOSERVER_ADMIN_USER=user
        - GEOSERVER_ADMIN_PASSWORD=password
        - STABLE_EXTENSIONS=charts-plugin,sqlserver-plugin,params-extractor-plugin
        - TOMCAT_EXTRAS=false
        - DISABLE_WEB_INTERFACE=false
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u user:'password' http://localhost:8600/geoserver/rest/about/version.xml"
      interval: 1m30s
      timeout: 10s
      retries: 3
```
2. add user vi api 
POST http://localhost:8600/geoserver/rest/security/usergroup/users/ 
request body : 
```
<?xml version="1.0" encoding="UTF-8"?>
<user>
    <userName>userxml</userName>
    <password>passwordxml</password>
    <enabled>true</enabled>
</user>
```
3. delete container and run docker compose up again (it will create a new container) Make sure you run a new container , not starting exising one 

4. Find in logs :  [Fatal Error] :-1:-1: Premature end of file 
Geoserver won't sucessfully start

This is local reproduction of the same issue that happens on kubernetes cluster

### Versions

Geoserver - 2.23.0
