### ISSUE TITLE
gdal stable extension support needed.

### ISSUE THREAD

**Issue by cetindogu** [kartoza/docker-geoserver#614]
### Feature description

gdal extension
for example i have .ecw files. i need the GDAL extension enabled.

**Comment by cetindogu** [comment]
how can i copy Gdal library *.jar files into /usr/local/tomcat/webapps/geoserver/WEB-INF/lib  directory
and set LD_LIBRARY_PATH=/usr/local/tomcat/webapps/geoserver/WEB-INF/lib

this is my docker-compose.yml file content.


```
version: '3'
services:
  geoserver:
    image: kartoza/geoserver:2.24.1
    container_name: geoserver
    ports:
      - "8600:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - SAMPLE_DATA=true
      - STABLE_EXTENSIONS=oracle-plugin
      - LD_LIBRARY_PATH=/usr/local/tomcat/webapps/geoserver/WEB-INF/lib:/usr/local/tomcat/native-jni-lib:/usr/local/tomcat/native-jni-lib:/usr/lib/jni:/usr/local/apr/lib:/opt/libjpeg-turbo/lib64:/usr/lib:/usr/lib/x86_64-linux-gnu
    volumes: 
      - ./GEOSERVER_DATA_DIR:/opt/geoserver/data_dir
      - ./geoserver_lib_dir:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib

```
