### ISSUE TITLE
 [geoserver.monitor] - Request Dumper exiting due to :Permission denied

### ISSUE THREAD

**Issue by datanui** [kartoza/docker-geoserver#628]
### What is the bug or the crash?

Using the image 2.24.2 within docker-compose, I get an error (WARN) from the monitor request dumper. A log file is actually created in data_dir/logs but as root user while the container user is ec2-user.

```
geoserver_1      | 14 039 22:39:46 WARN   [geoserver.monitor] - Request Dumper exiting due to :Permission denied
geoserver_1      | java.io.IOException: Permission denied
geoserver_1      |      at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
geoserver_1      |      at java.base/java.io.File.createNewFile(File.java:1035)
geoserver_1      |      at org.geoserver.monitor.auditlog.AuditLogger$RequestDumper.rollWriter(AuditLogger.java:385)
geoserver_1      |      at org.geoserver.monitor.auditlog.AuditLogger$RequestDumper.run(AuditLogger.java:276)
geoserver_1      | 14 039 22:39:46 INFO   [geoserver.monitor] - Request Dumper stopped
```

### Steps to reproduce the issue

```
  geoserver:
    image: geoserver
    networks:
      - mynetwork
    ports:
      - 8600:8080
    restart: always
    environment:
      - EXISTING_DATA_DIR=true
      - GEOWEBCACHE_CACHE_DIR=/my/gwc
      - CSRF_WHITELIST=example.com
      - REQUEST_TIMEOUT=30
      - HTTP_PROXY_NAME=example.com
      - HTTP_SCHEME=https
      - ROOT_WEBAPP_REDIRECT=true
      - ENABLE_JSONP=false
      - HOST=postgis
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASS=pass
      - POSTGRES_SCHEMA=public
      - DISK_QUOTA_SIZE=5
      - POSTGRES_JNDI=TRUE
    volumes:
      - ~/volumes/my/gwc:/my/gwc
      - ~/volumes/geoserver_data_dir:/opt/geoserver/data_dir
```
      

### Versions

GeoServer 2.24.2

### Additional context

AWS EC2 instance with Amazon Linux 2 behind ALB
