### ISSUE TITLE
Setting master password breaks the app after container restart

### ISSUE THREAD

**Issue by rokamon1997** [kartoza/docker-geoserver#743]
### What is the bug or the crash?

In the version `2.27.x` after logging in and changing the master password the bellow message gets logged: 
`Successfully changed master password`.

However, after restarting the container bellow error is seen in the logs:
```java
org.springframework.beans.factory.BeanCreationException: Error occured reading security configuration; nested exception is java.io.IOException: Keystore was tampered with, or password was incorrect
at org.geoserver.security.GeoServerSecurityManager.reload(GeoServerSecurityManager.java:429)
```

### Steps to reproduce the issue

1. Use this `docker-compose.yml` file to build the image and run the container.

```yml
services:
  scalar-geoserver:
    image: kartoza/geoserver:2.27.0
    container_name: geoserver
    ports:
      - "8085:8080"
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    volumes:
      - data_dir:/opt/geoserver/data_dir
      - gwc:/opt/geoserver/gwc
    restart: unless-stopped

volumes:
  data_dir:
  gwc:
```

2. Login as admin
3. Change master password
4. Restart container
5. App breaks

### Versions

kartoza/geoserver:2.27.0
