### ISSUE TITLE
GeoServer unable to validate HTTPS connection with self-signed cert added to truststore

### ISSUE THREAD

**Issue by BadShepard** [kartoza/docker-geoserver#744]
### What is the bug or the crash?

In a development environment, I'm trying to connect to a WFS service over HTTPS that uses a self-signed certificate. Despite importing the certificate into the Java truststore, I consistently encounter the following SSL handshake error:
> javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This occurs even though the certificate has been correctly placed and imported into the truststore. The environment variable USE_SYSTEM_CA_CERTS=true was set, and I also manually invoked the __cacert_entrypoint.sh script (and verified the cert was added). Additionally, I tried importing the certificate directly into the truststore manually with keytool, but the issue persists.

This is in a trusted development setup, so accepting self-signed certificates is intentional and secure for my use case.

[full-stack-trace.txt](https://github.com/user-attachments/files/20303510/full-stack-trace.txt)

### Steps to reproduce the issue

1. Use the following docker-compose.yaml:
```yaml
version: '3.2'
services:
    geoserver:
      image: kartoza/geoserver:2.27.0
      container_name: geoserver
      volumes:
        - "./data_dir:/opt/geoserver/data_dir"
        - "./certs:/certificates"
      ports:
        - "8600:8080"
      environment:
        - EXISTING_DATA_DIR=true
        - GEOSERVER_ADMIN_PASSWORD=geoserver
        - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
        - ENABLE_JSONP=true
        - MAX_FILTER_RULES=20
        - OPTIMIZE_LINE_WIDTH=false
        - FOOTPRINTS_DATA_DIR=/opt/footprints_dir
        - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
        - USE_SYSTEM_CA_CERTS=true
```
2. Place the certificate .crt file into the ./certs directory.
3. Start the container.
4. Run __cacert_entrypoint.sh inside the container.
5. Verify the certificate is in the truststore using keytool -list.
6. Attempt to connect to a WFS service using HTTPS.
<br/>
Also I tried manually adding certificate to the store inside the container:

`keytool -import -trustcacerts -alias my-cert -keystore ${JAVA_HOME}/lib/security/cacerts -file /certificates/my-cert.crt -noprompt -storepass changeit`

### Versions

2.27.0
